name: Compile LaTeX document

on:
  push:
    paths:
      - '**.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: resume.tex
    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: Compiled PDF
        path: ${{ github.workspace }}/*.pdf
